context("test correspondence analysis")
test_that("test exp_mca", {
  model_df <- mtcars %>% exp_mca(vs,am,gear,carb, ncp=5, quanti_sups=c("mpg","disp","hp","drat","wt","qsec"))
  res <- model_df %>% tidy_rowwise(model, type="contrib")
  expect_equal(colnames(res), c("Category","Dimension","Value"))
  res <- model_df %>% tidy_rowwise(model, type="variance")
  expect_equal(colnames(res), c("eigenvalue","percentage of variance","cumulative percentage of variance","dim"))
  res <- model_df %>% tidy_rowwise(model, type="quanti_sup")
  expect_equal(colnames(res), c("variable","Dimension 1","Dimension 2"))
  res <- model_df %>% tidy_rowwise(model, type="data")
  expect_equal(colnames(res), c("mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb","Dimension 1","Dimension 2","Dimension 3","Dimension 4","Dimension 5"))
  res <- model_df %>% tidy_rowwise(model, type="categories")
  expect_equal(res[[1,3]], -0.6075913, tolerance = 0.001)
  expect_equal(colnames(res), c("variable","category","Dimension 1","Dimension 2"))
  res <- model_df %>% tidy_rowwise(model, type="variables")
  expect_equal(colnames(res), c("variable","Dimension 1","Dimension 2"))
})
